name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words:  ^3.1.0
  dio: ^0.0.14
  json_annotation:  ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^0.7.6
  json_serializable: ^0.3.2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icon/home_normal.png
    - assets/icon/home_seleted.png
    - assets/icon/learn_normal.png
    - assets/icon/learn_seleted.png
    - assets/icon/community_normal.png
    - assets/icon/community_seleted.png
    - assets/icon/mine_normal.png
    - assets/icon/mine_seleted.png
    - assets/icon/user_avatar.png
    - assets/icon/app_logo.png
    - assets/icon/icon_qq.png
    - assets/icon/icon_wechat.png
    - assets/icon/icon_sina.png
    - assets/icon/icon_scan.png
    - assets/icon/message_normal.png
    - assets/icon/message_seleted.png
    - assets/icon/icon_wrong.png
    - assets/icon/icon_exercise.png
    - assets/icon/icon_language.png
    - assets/icon/icon_histroy.png
    - assets/icon/icon_geography.png
    - assets/icon/icon_exercise.png
    - assets/icon/icon_political.png
    - assets/icon/icon_math.png
    - assets/icon/icon_physical.png
    - assets/icon/icon_biological.png
    - assets/icon/icon_english.png
    - assets/icon/icon_right.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
